### ISSUE TITLE
No ESLint configuration Error

### ISSUE THREAD

**Issue by vishnubhadri** [team-innovation/vue-sfc-rollup#103] opened 2021-07-13 15:37 UTC
Hi. i created library using vue-sfc-rollup and builded.
after connecting with npm link to another app and imported it show below error.
```
 ERROR  Failed to compile with 1 error                                                                                                        9:03:20 PM
Syntax Error: Error: No ESLint configuration found in F:\sfc-test\dist.


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

**Comment by mgdodge** [comment] 2021-07-14 05:22
You cannot expect proper behavior when installing via `npm link`, unfortunately. This has come up [numerous times](https://github.com/team-innovation/vue-sfc-rollup/issues/94#issuecomment-842315854) in [prior issues](https://github.com/team-innovation/vue-sfc-rollup/issues/96#issuecomment-839757179) and the problem is with the way webpack resolves modules installed in this manner. The guaranteed solution is to install from a .tgz file (created via `npm pack`). I believe you can also just delete the node_modules directory from within the component, itself prior to running `npm link` in the consuming app, as that will cause webpack to install the dependencies properly, though I can't be 100% sure on that.

Closing this issue, as it is a documented issue that must be resolved elsewhere, not with the code generated by vue-sfc-rollup.

**Closed by mgdodge** 2021-07-14 05:22 UTC
