### ISSUE TITLE
Updating rollup to a more recent version breaks the project

### ISSUE THREAD

**Issue by leoclipet** [team-innovation/vue-sfc-rollup#68] opened 2021-01-15 15:32 UTC
Hello,

When updating the rollup dependency to a more recent one (I tried the last one), rollup can not resolve anymore

`import * as components from '@/components/index';` from `entry.ts`

Any idea on what to fix?

**Comment by mgdodge** [comment] 2021-01-16 16:33
Was the update for rollup itself, or a rollup plugin? Also, were other dependencies updated at the same time, or just one? Not enough detail here to even start a guess.

Also, this is not a bug with vue-sfc-rollup itself, but more an issue with your rollup configuration/npm dependencies. As a result, I am going to close this issue, with the recommendation that you look at the latest beta version of vue-sfc-rollup and use it to create a "test" library with typescript support, then compare the config/package.json with your own. You might find something there that you can use to get your library build working again.

The beta version is just about ready to be released as a new major version - just hoping one upstream bug can get fixed first, but I have been waiting long enough I am tempted to release it anyway with a note of the issue.

**Closed by mgdodge** 2021-01-16 16:33 UTC
