### ISSUE TITLE
Cant run on a typescript vue project

### ISSUE THREAD

**Issue by acamenhas** [team-innovation/vue-sfc-rollup#34] opened 2020-02-03 11:14 UTC
Hi all,

I've created a new project > Library > Typescript for my Vue components.

In this test, i leave all the files generated and just "clean" the sample component:

![comp2](https://user-images.githubusercontent.com/14015712/73648311-37d44e80-4675-11ea-9fe7-daa6d37330ef.png)

Then, made a build and published, all ok.

When i import this component in a typescript project it gives me following error, and anyone gives me an hint?

![comp3](https://user-images.githubusercontent.com/14015712/73648713-0f008900-4676-11ea-85a0-52735ed1c96a.png)

![comp4](https://user-images.githubusercontent.com/14015712/73648728-13c53d00-4676-11ea-8408-6c8df4bfa239.png)

If i import them in a "normal" vue project, everything runs well.

Thank you

**Comment by mgdodge** [comment] 2020-02-03 13:51
When you are importing individual components from the library, as you seem to be doing here, the import statement should be written thus:

`import { TestingsfcSample } from 'testingsfc'`

The package is compiled in such a way that you can import the entire library as a whole via the `default` export, or individual components as needed via the named exports. By leaving out the `{}` curly braces, you are using the default export (and in this case, just *calling* it TestingsfcSample). Adding in the braces will instead load just the *named export* TestingsfcSample. This is a common pattern for packages, detailed in [this popular post](https://medium.com/@timoxley/named-exports-as-the-default-export-api-670b1b554f65).

I can confirm that both of these scenarios, as I have described, work as intended. I am going to go ahead and close this issue.

**Closed by mgdodge** 2020-02-03 13:51 UTC

**Comment by acamenhas** [comment] 2020-02-03 15:29
Hi @mgdodge thank you for your reply, it worked!
The problem now is then i have 2 components, when i import one of them, i get this error:

`import { Span } from 'testingsfc'`

`Module '"../node_modules/testingsfc/testingsfc"' has no exported member 'Span'. Did you mean to use 'import Span from "../node_modules/testingsfc/testingsfc"' instead?` 

In my src>lib-components>index.ts i'm exporting this way:
`export { default as Span } from './Span.vue';
export { default as OneColumn } from './OneColumn.vue';`

**Comment by mgdodge** [comment] 2020-02-04 20:57
In the root directory of the repository, there is a `.d.ts` file which you must keep up to date similar to the `src/lib-components/index.ts` file. That is the source of the error.
