### ISSUE TITLE
UMD imports are not working

### ISSUE THREAD

**Issue by nanome-web** [team-innovation/vue-sfc-rollup#13] opened 2019-01-15 04:01 UTC
I just tried a completely fresh library creation with a completely fresh Vue CLI3 project, and it's not working. After installing and then importing the library, I get this error in the browser console:

`example.umd.js?8378:2 - Uncaught TypeError: Cannot set property 'Example' of undefined`

Steps to reproduce:
1. `vue create my-project`
2. Fill out prompts
3. `cd my-project`
4. `npm install -g vue-sfc-rollup`
5. `sfc-rollup-init`
6. Select Library option, and name "example"
7. `cd example`
8. `npm install`
9. `npm run build`
10. Add `import Example from '../example/dist/example.umd'`

That may have been verbose, but if I console.log(Example) or Vue.use(Example) I still get this same error. And also in the terminal while building the project `"export 'default' (imported as 'example') was not found in '../test/dist/example.umd'`

**Comment by mgdodge** [comment] 2019-01-15 18:23
This can be easily remedied by not importing the UMD build, but the ESM (modern) build instead. Note this [vue cookbook article](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#How-does-npm-know-which-version-to-serve-to-a-browser-build-process), specifically the section on which version is used in browsers/build processes.

In your example, you are using the CLI build process, which is using webpack behind the scenes. By forcing the UMD build you are forcing one that webpack doesn't handle well. If you change your import statement to `import Example from '../example'` then webpack will look at the package.json for the component/lib, identify the 'module' version, and everything works. Your `Vue.use(Example)` would then register it with Vue.

UMD is primarily provided for use in RequireJS and other legacy module-loading scenarios. Incidentally, it can sometimes also be used directly in browsers via script tag, though the minified version is the one optimized for that scenario.

Closing this as it is not a bug of vue-sfc-rollup. UMD is created by rollup, consumed by webpack, so if you really need to use UMD in this way, the solution would have to come from one of those.

**Closed by mgdodge** 2019-01-15 18:23 UTC
Labels: wontfix

**Comment by mgdodge** [comment] 2019-01-16 02:47
Try the new release from today. UMD wouldn't have worked regardless, but esm did have an bug in library mode which is now fixed. You might now be running into issue #14, which was fixed by today's v1.0.3 release.

**Comment by Stegosource** [comment] 2019-01-16 03:10
Yes. That was the issue. Thanks again for putting the time into this. It's exactly what I was looking for, and the Vue community is better off thanks to you :)
