### ISSUE TITLE
CSS & plain text appears to be missing (Vue 3, TS)

### ISSUE THREAD

**Issue by jackdomleo7** [team-innovation/vue-sfc-rollup#96] opened 2021-05-12 10:22 UTC
Repro steps:

Step 1: Create component library
- `npm i -g vue-sfc-rollup@4.0.5`
- `$ sfc-init`
  - Vue 3
  - TypeScript
- `cd <component library>`
- `npm i`
- `npm run build`

Step 2: Create a regular Vue 3 project
- `npx @vue/cli create my-project`
  - Choose Vue 3 & TypeScript
- `cd my-project`
- `npm i ../path/to/component-library` (alternatively use `npm link` - both methods produce same results here)
- In a Vue file, import the default Sample Vue component from `vue-sfc-rollup` and add to HTML
- `npm run serve`

Expected results:
_This is what I see when running `npm run serve` in the component library project, so expect to see this in regular Vue 3 project once imported._
![image](https://user-images.githubusercontent.com/43371432/117959077-932ecb00-b313-11eb-8560-81bb5bd5733e.png)

Actual results:
_When imported into regular Vue 3 project, run `npm run serve`, it seems that CSS and plain text is missing._
![image](https://user-images.githubusercontent.com/43371432/117959126-9e81f680-b313-11eb-8d28-5158e57b4cea.png)
![image](https://user-images.githubusercontent.com/43371432/117959160-a477d780-b313-11eb-87aa-2b5736e20d07.png)

Got some colleagues to perform the same steps and they get the same results with `vue-sfc-rollup@4.0.5`. Is this a bug or are we missing something? Also, I mentioned this in #83 but #83 was closed so thought best to create a new issue. Just to clarify, I haven't altered any config, I am using the default generated project structure & config from `sfc-init`.

Thanks.

**Comment by jackdomleo7** [comment] 2021-05-12 12:47
Apologies! This actually seems to be a problem with `npm link` and local `npm i ./path/to/library`. When publishing the library and installing from the npm registry, it works fine and as expected.

Sorry for the issue (but something to keep in mind) and thank you for this great tool!

**Comment by mgdodge** [comment] 2021-05-12 13:06
I was actually in the process of writing the following when you made your comment. Closing this as it is not a bug with vue-sfc-rollup, but leaving this information here for anyone who happens to come across it:

---

Running step 1 this morning on a fresh install, I can see the output includes the CSS and text, so vue-sfc-rollup and all its dependencies are working as they should there.

Running step2, I can indeed duplicate the missing text/styles.

**_However, if you package the component/lib first via `npm pack`, then install from the resulting `.tgz` file, everything works fine!_**

I have seen funny issues before when installing things via `npm link` or other methods - and not just vue components. I can't say for sure, but in this case I believe the issue might be due to how webpack resolves things.

Technically, `npm pack` is exactly what happens behind the scenes when you publish a library, so it's actually closer to what your users would see. It is more inconvenient, true, but it eliminates all the other stuff - and in this case, that is where the problems lie.

I have a few ideas:

- install via `npm pack` when consuming in another app, or
- install via `npm pack` and then create a symlink from `node_modules/<component-library>/dist` to the source `<component-library>/dist` folder - essentially symlinking only the dist directory instead of the entire module. I've used this before in other weird npm cases. Might be worth a try here.
- dive deeper into how webpack and `npm link` interact.

I've taken a quick look at tweaking the webpack config via `vue.config.js` but haven't hit upon the right combination yet. I am aware others have used [this comment](https://github.com/vuejs/vue-cli/issues/1494#issuecomment-498144990) with success, but it doesn't seem to be working for me here. Only tried a little though.

**Closed by mgdodge** 2021-05-12 13:06 UTC
